
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mavile
    username: mavile
    password: mavile
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: liquibase/changelog.xml
logging:
  level:
    root: DEBUG