
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SpringTask
    username: User
    password: 12345
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: liquibase/scripts/changelog-2.sql